name: Build and Release Electron App

on:
  release:
    types: [created]
  push:
    branches:
      - main
      
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Change directory to frontend
        run: cd frontend

      - name: Install frontend dependencies
        run: npm install  # or yarn install, depending on your project setup

      - name: Build frontend
        run: npm run build  # or yarn build, depending on your project setup

      - name: Navigate back to root directory
        run: cd ..

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
