name: Build and Release Electron App

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build and Release Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          args: --linux deb appImage
        env:
          ELECTRON_CACHE: "/home/runner/.cache/electron"
          ELECTRON_BUILDER_CACHE: "/home/runner/.cache/electron-builder"
        working-directory: ./frontend
